#!/usr/bin/env python3
"""Download official names per language from PokeAPI and write tools/dex_names.py.

  python3 tools/gen_names.py

Only FR and DE have unique names in gen 1; ES/IT/PT use English, so
only names that differ from English are stored here. The GFX font is
ASCII, so names are uppercase and unaccented.
"""
import json
import os
import subprocess
import time
import unicodedata

LANGS = ('fr', 'de')


def ascii_up(s):
    """'Salameche' -> 'SALAMECHE'; keeps gender symbols as f/m."""
    s = s.replace('♀', 'F').replace('♂', 'M')  # Nidoran female/male
    s = unicodedata.normalize('NFD', s)
    s = ''.join(c for c in s if unicodedata.category(c) != 'Mn')
    return s.upper()


def fetch(num):
    url = f'https://pokeapi.co/api/v2/pokemon-species/{num}/'
    for intento in range(4):
        r = subprocess.run(['curl', '-s', '--max-time', '25', '-A', 'Mozilla/5.0', url],
                           capture_output=True, text=True)
        if r.returncode == 0 and r.stdout.strip().startswith('{'):
            return json.loads(r.stdout)
        time.sleep(1 + intento)
    raise SystemExit(f'could not download species {num}')


def main():
    out = {}
    for num in range(1, 152):
        d = fetch(num)
        names = {n['language']['name']: n['name'] for n in d['names']}
        en = ascii_up(names['en'])
        dif = {}
        for lg in LANGS:
            v = ascii_up(names.get(lg, names['en']))
            if v != en:
                dif[lg] = v
        if dif:
            out[num] = dif
        if num % 25 == 0:
            print(f'  {num}/151...')
        time.sleep(0.05)

    path = os.path.join(os.path.dirname(__file__), 'dex_names.py')
    with open(path, 'w', encoding='utf-8') as f:
        f.write('# -*- coding: utf-8 -*-\n')
        f.write('"""GENERATED by tools/gen_names.py from PokeAPI - do not edit by hand.\n\n')
        f.write('Official names that differ from English (FR and DE only in gen 1),\n')
        f.write('uppercase and unaccented because the GFX font is ASCII.\n"""\n\n')
        f.write('LOCAL_NAMES = {\n')
        for num in sorted(out):
            f.write(f'    {num}: {out[num]!r},\n')
        f.write('}\n')
    print(f'saved {os.path.normpath(path)}: {len(out)} species with unique names')


if __name__ == '__main__':
    main()
